name: Continuous Integration
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: ls
      - run: cd backend
      - run: ls
      - run: npm i
      - run: npm run build
