name: Continuous Integration
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-cache

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Deps
        run: cd backend && npm i

      - name: build
        run: cd backend && npm run build

      # - name: Generate Artifacts
      #   run: cd backend/build && zip -r artifact.zip ./ -x '*.git*'

      - name: Generate Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: backend/dist

      # - name: Store Artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: backend
      #     path: backend/build/artifact.zip
